version: "3.2"

services:
  demo1:
    image: cdunkelb/service2
    deploy:
      replicas: 1
      labels:
        com.docker.lb.hosts: demo.cdunkelb.com
        com.docker.lb.network: demo2
        com.docker.lb.port: 80
        com.docker.lb.context_root: /app2
        com.docker.lb.context_root_rewrite: "true"
    networks:
      - demo2

networks:
  demo2:
    driver: overlay